app/Dockerfile
app/package-lock.json
app/package.json
strapi/.nsprc

Pipeline: include additional files in docker image

---

.github/workflows/publish-images.sh
strapi/.nsprc

pipeline: update container registry for releases

---

strapi/.nsprc

Closes https://github.com/openkfw/innoverse/issues/62

security: ignore CVE-2024-47068 until 31.10.2024

---

app/components/collaboration/emojiReactions/EmojiPicker.tsx

https://github.com/openkfw/innoverse/issues/48#issuecomment-2371384995

Upgrade Emoji-Version @emoji-mart/data

---

app/.nsprc
app/next.config.js
strapi/.nsprc

fix: rename allowed_origins in next.config.js

---

app/messages/de.json
app/messages/en.json
strapi/.nsprc

fix: standardize wording from updates to news de/en

---

app/components/landing/feedbackSection/FeedbackSection.tsx

fix: feedback button now always visible

---

app/app/export/actions.ts
app/pages/api/auth/[...nextauth].ts
app/utils/auth.ts
app/utils/requests/collaborationComments/requests.ts
app/utils/requests/collaborationQuestions/requests.ts
app/utils/requests/events/requests.ts
app/utils/requests/innoUsers/requests.ts
app/utils/requests/opportunities/requests.ts
app/utils/requests/pageRequests.ts
app/utils/requests/surveyQuestions/requests.ts
app/utils/requests/updates/requests.ts

Error when creating the InnoUser

---

app/components/project-details/CollaborationColumn.tsx
app/components/project-details/TabView.tsx
app/components/project-details/UpdateCard.tsx

Closes #124 
Refactored scrolling logic on the project page 
Added smooth scrolling when switching tabs
Fixed issues with misdirected scrolling on the "alle news" tab

Fix project page scrolling

---

app/components/common/project/ContentCard.tsx
app/components/landing/featuredProjectSection/slider/FeaturedProjectContent.tsx
app/components/landing/mappingProjectsSection/MappingProjectsCard.tsx
app/components/landing/mappingProjectsSection/PhaseColumns.tsx
app/components/project-details/VisibleContributors.tsx

Closes #115 
Removed layout shifts in PhaseColumns descriptions
Removed layout shifts in the main slider

fix: Layout shift in homepage

---

app/components/newsPage/threads/NewsCommentThread.tsx
app/components/newsPage/threads/NewsUpdateThread.tsx
app/components/newsPage/threads/actions.ts
app/services/commentService.ts
app/utils/newsFeed/redis/helpers.ts
app/utils/newsFeed/redis/redisClient.ts
app/utils/newsFeed/redis/redisService.ts
app/utils/newsFeed/redis/services/commentsService.tsx

Bug: Allow full text search for comments (e.g. multiple words with spaces)

---

app/app/page.tsx
app/components/landing/newsSection/NewsSection.tsx

fix: More news button not clickable

---

app/package-lock.json
app/package.json

to fix the problem described here https://github.com/prisma/prisma/issues/20479, an upgrade to [prisma 6.1.0](https://github.com/prisma/prisma/releases/tag/6.1.0) is needed

refactor: update prisma to 6.1.0

---

app/components/common/comments/WriteCommentResponseCard.tsx
app/components/newsPage/threads/CommentThread.tsx
app/services/commentService.ts
app/utils/newsFeed/redis/redisService.ts
app/utils/newsFeed/redis/services/commentsService.tsx

Bug in comment count

---

app/.env.example
app/components/collaboration/comments/actions.ts
app/components/landing/feedbackSection/actions.ts
app/components/newsFeed/NewsFeedTypeFilter.tsx
app/config/server.js
app/services/collaborationCommentService.ts
app/utils/newsFeed/newsFeedSync.ts
app/utils/newsFeed/redis/mappings.ts
app/utils/requests/comments/mapping.ts
docs/developer/START_UP_GUIDE.md

Bug: Collaboration Comment fixes

---

app/components/newsPage/threads/CommentThread.tsx
app/components/newsPage/threads/NewsCommentThread.tsx
app/pnpm-lock.yaml
app/utils/newsFeed/redis/services/commentsService.tsx

Fix bugs in Comments

---

app/app/api/hooks/push/route.ts
app/app/api/notification/update-subscription/route.ts

Closes #191 
Changed the Route handlers (headers, body) based on the next [docs](https://nextjs.org/docs/app/building-your-application/routing/route-handlers).

Bug: Strapi webhooks are not triggered

---

app/app/api/hooks/push/route.ts
app/utils/strapiEvents/entityLifecycles/collaborationQuestionLifecycle.ts
app/utils/strapiEvents/entityLifecycles/eventLifecycle.ts
app/utils/strapiEvents/entityLifecycles/opportunityLifecycle.ts
app/utils/strapiEvents/entityLifecycles/projectLifecycle.ts
app/utils/strapiEvents/entityLifecycles/strapiEntityLifecycle.ts
app/utils/strapiEvents/entityLifecycles/surveyQuestionLifecycle.ts
app/utils/strapiEvents/entityLifecycles/updateLifecycle.ts
app/utils/strapiEvents/strapiEventHandler.ts
strapi/types/generated/contentTypes.d.ts

Closes #199 
How to test:
- Make sure you have webhook set in Strapi based on the [docs](https://github.com/openkfw/innoverse/blob/main/docs/developer/START_UP_GUIDE.md#cms-setup)
- change e.g. an Event in Strapi
- the event item should be changed in the cache and shown in the FE on the News Feed Page

Bug: Rename id to documentId in Strapi webhook lifecycles

---

app/components/common/InteractionButton.tsx
app/components/common/form/AutocompleteDropdownField.tsx
app/components/common/form/CheckboxInputField.tsx
app/components/common/form/formStyle.tsx
app/components/newsPage/addPost/form/AddPostForm.tsx
app/components/newsPage/addUpdate/form/AddUpdateForm.tsx
app/styles/palette.ts
app/utils/newsFeed/newsFeedSync.ts

Closes #212 
- fixed styling of the inputs in the News Feed dialog/form

Bug: Incorrect styling in "Beitrag hinzufügen" dialog in the News Feed

---

CHANGELOG.md
app/package.json
strapi/package.json

Revert "chore(release): 1.4.1"

---

app/app/skeletonIndexPage.tsx
app/components/common/CustomDialog.tsx
app/components/login/LoginDialog.tsx
app/components/login/UserSuggestionRow.tsx
app/package.json
app/pnpm-lock.yaml

Closes #177 
- Do not fetch any data from Strapi before the user logs in
- Style a new LogIn Page
- Update `react-router` lib due to the vulnerability

Prevent content from showing before login

---

app/app/contexts/news-feed-context.tsx
app/components/newsPage/cards/common/NewsCardActions.tsx

Bug: Editing controls shown for unauthorized users

---

app/config/client.js
app/config/server.js
app/instrumentation.ts
app/utils/instrumentation/AppInsights.ts
docs/developer/START_UP_GUIDE.md

Closes #264 
Updated the implementation to make Azure Insights environment variables optional.
Updated the docs

Update Azure Insights variables to be non-mandatory
